import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../hooks/useAppContext';
import { getCodingProblem, evaluateCode } from '../utils/api';
import { ScoreRing, Chip, ProgressBar, Skeleton, ErrorBox } from '../components/UI';

const DIFFICULTIES = ['Easy', 'Medium', 'Hard'];
const LANGUAGES = ['Python', 'Java', 'JavaScript', 'C++'];

export default function CodingPage() {
  const navigate = useNavigate();
  const { profile, codingResult, setCodingResult, markComplete } = useApp();

  const [phase, setPhase] = useState('intro');
  const [problem, setProblem] = useState(null);
  const [code, setCode] = useState('');
  const [language, setLanguage] = useState('Python');
  const [difficulty, setDifficulty] = useState('Medium');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function loadProblem() {
    setLoading(true); setError('');
    try {
      const { data } = await getCodingProblem(profile.role, difficulty);
      setProblem(data);
      setCode(data.starter_code_python || '# Write your solution here\n');
      setPhase('editor');
    } catch (e) {
      setError(e.response?.data?.error || e.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleEvaluate() {
    if (!code.trim()) return;
    setLoading(true); setError('');
    try {
      const { data } = await evaluateCode({
        code,
        language,
        problem_title: problem?.title,
        role: profile.role,
      });
      setCodingResult(data);
      markComplete('coding');
      setPhase('result');
    } catch (e) {
      setError(e.response?.data?.error || e.message);
    } finally {
      setLoading(false);
    }
  }

  /* ── Intro ── */
  if (phase === 'intro') {
    return (
      <div>
        <div className="page-header">
          <h1>Coding Assessment</h1>
          <p>Your code is evaluated by <strong>Code2Vec</strong> — analysing structure, logic paths, and token embeddings.</p>
        </div>
        <div className="card" style={{ maxWidth: 560 }}>
          <div style={{ fontWeight: 600, marginBottom: 16 }}>Problem Settings</div>
          <div className="form-group">
            <label className="form-label">Difficulty</label>
            <div style={{ display: 'flex', gap: 8 }}>
              {DIFFICULTIES.map(d => (
                <button key={d} onClick={() => setDifficulty(d)}
                  className={`btn btn-sm ${difficulty === d ? 'btn-primary' : 'btn-outline'}`}>{d}</button>
              ))}
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Language</label>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {LANGUAGES.map(l => (
                <button key={l} onClick={() => setLanguage(l)}
                  className={`btn btn-sm ${language === l ? 'btn-primary' : 'btn-outline'}`}>{l}</button>
              ))}
            </div>
          </div>
          <div style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 16 }}>
            A role-specific coding problem will be generated by Claude AI for <strong>{profile.role}</strong>.
          </div>
          <ErrorBox message={error} />
          <button className="btn btn-primary" onClick={loadProblem} disabled={loading}>
            {loading ? '⏳ Generating problem...' : '▶ Get Problem'}
          </button>
          {codingResult && (
            <button className="btn btn-outline" style={{ marginLeft: 12 }} onClick={() => setPhase('result')}>
              View Previous Result
            </button>
          )}
        </div>
      </div>
    );
  }

  /* ── Editor ── */
  if (phase === 'editor' && problem) {
    return (
      <div>
        <div className="page-header">
          <h1>Coding Assessment</h1>
          <p>Write your solution and submit for Code2Vec analysis.</p>
        </div>

        <div className="grid-2">
          {/* Problem */}
          <div className="card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <div style={{ fontWeight: 600 }}>{problem.title}</div>
              <div style={{ display: 'flex', gap: 8 }}>
                <Chip variant={difficulty === 'Hard' ? 'red' : difficulty === 'Medium' ? 'amber' : 'green'}>{difficulty}</Chip>
                <Chip variant="accent">{language}</Chip>
              </div>
            </div>

            <div style={{ background: 'var(--bg3)', borderRadius: 'var(--r)', padding: 16, marginBottom: 16 }}>
              <p style={{ fontSize: 14, lineHeight: 1.7, marginBottom: 12 }}>{problem.description}</p>

              {problem.constraints?.length > 0 && (
                <div style={{ marginBottom: 12 }}>
                  <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 6, textTransform: 'uppercase' }}>Constraints</div>
                  {problem.constraints.map((c, i) => <div key={i} style={{ fontSize: 13 }}>• {c}</div>)}
                </div>
              )}

              {problem.examples?.map((ex, i) => (
                <div key={i} style={{ marginTop: 10, background: 'var(--bg)', borderRadius: 8, padding: 10 }}>
                  <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 4 }}>Example {i + 1}</div>
                  <div style={{ fontFamily: 'monospace', fontSize: 12, color: 'var(--teal)' }}>Input: {ex.input}</div>
                  <div style={{ fontFamily: 'monospace', fontSize: 12, color: 'var(--accent2)' }}>Output: {ex.output}</div>
                  {ex.explanation && <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 4 }}>{ex.explanation}</div>}
                </div>
              ))}
            </div>

            {problem.hints?.length > 0 && (
              <details style={{ fontSize: 13, color: 'var(--muted)' }}>
                <summary style={{ cursor: 'pointer', marginBottom: 6 }}>💡 Hints</summary>
                {problem.hints.map((h, i) => <div key={i} style={{ padding: '4px 0' }}>• {h}</div>)}
              </details>
            )}
          </div>

          {/* Editor */}
          <div className="card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <div style={{ fontWeight: 600 }}>Your Solution</div>
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="btn btn-outline btn-sm" onClick={() => setCode(problem.starter_code_python || '')}>Reset</button>
              </div>
            </div>
            <textarea
              className="code-editor"
              value={code}
              onChange={e => setCode(e.target.value)}
              spellCheck={false}
            />
            <ErrorBox message={error} />
            <div style={{ display: 'flex', gap: 12, marginTop: 12 }}>
              <button className="btn btn-outline btn-sm" onClick={() => setPhase('intro')}>← New Problem</button>
              <button className="btn btn-primary" onClick={handleEvaluate} disabled={loading || !code.trim()}>
                {loading ? '⏳ Running Code2Vec...' : '⚙ Evaluate Code'}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ── Result ── */
  if (phase === 'result' && codingResult) {
    const d = codingResult;
    const col = d.overall_score >= 80 ? 'var(--teal)' : d.overall_score >= 60 ? 'var(--accent)' : 'var(--amber)';
    return (
      <div>
        <div className="page-header">
          <h1>Code2Vec Analysis</h1>
          <p>Structural embedding analysis complete.</p>
        </div>

        <div className="grid-2 mb-16">
          <div className="card" style={{ textAlign: 'center', padding: 32 }}>
            <ScoreRing score={d.overall_score} color={col} size={130} label="Code Score" />
            <Chip variant={d.overall_score >= 80 ? 'teal' : d.overall_score >= 60 ? 'accent' : 'amber'} style={{ marginTop: 16 }}>
              {d.verdict}
            </Chip>
            <p style={{ fontSize: 13, color: 'var(--muted)', marginTop: 10 }}>
              {d.test_cases_passed}/5 hidden test cases passed
            </p>
            <div style={{ marginTop: 12, display: 'flex', gap: 8, justifyContent: 'center', flexWrap: 'wrap' }}>
              <Chip variant="teal">⏱ {d.time_complexity}</Chip>
              <Chip variant="accent">💾 {d.space_complexity}</Chip>
            </div>
          </div>

          <div className="card">
            <div style={{ fontWeight: 600, marginBottom: 16 }}>Dimension Scores</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <ProgressBar label="Correctness" right={`${d.correctness}%`} value={d.correctness} color="var(--teal)" />
              <ProgressBar label="Modularity" right={`${d.modularity}%`} value={d.modularity} color="var(--accent)" />
              <ProgressBar label="Readability" right={`${d.readability}%`} value={d.readability} color="var(--pink)" />
              <ProgressBar label="Efficiency" right={`${d.efficiency}%`} value={d.efficiency} color="var(--amber)" />
            </div>
          </div>
        </div>

        <div className="grid-2 mb-16">
          {/* Code2Vec tokens */}
          <div className="card">
            <div style={{ fontWeight: 600, marginBottom: 10 }}>Code2Vec Attention Tokens</div>
            <p style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 12 }}>{d.logic_flow_summary}</p>
            <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 8, textTransform: 'uppercase' }}>Key Tokens ({d.code2vec_path_count} paths analysed)</div>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {d.code2vec_attention_tokens?.map((t, i) => (
                <span key={i} style={{ background: 'var(--bg3)', border: '1px solid var(--accent)', borderRadius: 6, padding: '4px 10px', fontFamily: 'monospace', fontSize: 12, color: 'var(--accent2)' }}>{t}</span>
              ))}
            </div>
          </div>

          {/* Feedback */}
          <div className="card">
            <div style={{ fontWeight: 600, marginBottom: 10 }}>Feedback</div>
            <div style={{ marginBottom: 14 }}>
              <div style={{ fontSize: 11, color: 'var(--green)', marginBottom: 8, textTransform: 'uppercase' }}>✓ Well done</div>
              {d.positive_aspects?.map((p, i) => <div key={i} style={{ fontSize: 13, padding: '4px 0', borderBottom: '1px solid var(--border)' }}>• {p}</div>)}
            </div>
            <div>
              <div style={{ fontSize: 11, color: 'var(--amber)', marginBottom: 8, textTransform: 'uppercase' }}>→ Improvements</div>
              {d.improvements?.map((p, i) => <div key={i} style={{ fontSize: 13, padding: '4px 0', borderBottom: '1px solid var(--border)' }}>• {p}</div>)}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 12 }}>
          <button className="btn btn-outline" onClick={() => setPhase('intro')}>Try Another Problem</button>
          <button className="btn btn-primary" onClick={() => navigate('/interview')}>Proceed to HR Interview →</button>
        </div>
      </div>
    );
  }

  return null;
}
